LangString addOrReinstall ${LANG_SIMPCHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择要执行的操作，然后点击“下一步”继续。"
LangString appRunning ${LANG_SIMPCHINESE} "${PRODUCTNAME} 正在运行。请先关闭程序后再重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "${PRODUCTNAME} 正在运行。$\n点击“确定”将结束该进程。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装器不允许在不卸载的情况下执行降级安装）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法结束 ${PRODUCTNAME}。请先手动关闭程序后再重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 Microsoft Edge WebView2 Runtime..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装较新版本的 ${PRODUCTNAME}。不建议安装旧版本。如确需安装旧版本，建议先卸载当前版本。请选择要执行的操作，然后点击“下一步”继续。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装 $R4 版本的 ${PRODUCTNAME}。建议先卸载当前版本后再安装。请选择要执行的操作，然后点击“下一步”继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装器不允许降级安装，无法继续静默安装。请改用图形界面安装器。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载。"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前先卸载"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "WebView2 安装失败。缺少 WebView2 时应用无法运行，请重启安装器后重试。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：WebView2 下载失败 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 bootstrapper 下载完成"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 bootstrapper..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：WebView2 安装失败，退出码 $1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装完成"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除应用数据"
